### PR TITLE
Added import  fetch  from "node-fetch";

### PR DESCRIPTION
**Pull request by ChrisPhillips-cminion**
I need to add the import for fetch. this is only if you are running cert versions of node but I do not believe it will cause any issues

### CODE REVIEW

**Comment by ChrisPhillips-cminion** [comment]
Oh and parents now works

**Comment by jamesatjaminit** [comment]
Hey Chris,

Thank you for your pull request. However, I'm hesitant about merging it currently

Given that this package now targets both Node.js and Deno, the proposed changes break compatibility with Deno. Additionally, there's a compatibility issue with Node.js, which I believe stems from the omission of `node-fetch` in the `package.json` file.

On a broader note, I'm hesitant to support such an outdated version of Node.js, considering that fetch is now a built-in feature. I would prefer to minimise dependencies wherever possible.

Additionally, Node.js version 20.9.0 was recently promoted to LTS, making the version without native fetch support two major LTS versions behind. Could you elaborate on your use case for requiring such an old version?

**Comment by jamesatjaminit** [comment]
Thinking about it more, I think there's two ways to tackle this, if non-standard fetch support is needed:

1. Adding adapters - When init'ing the client, instead of importing `classcharts-api`, you'd import `classcharts-api/axios` or `classcharts-api/node-fetch` to use the respective fetch library.
2. Adding custom fetch support - Instead of supporting specific adapters, we could allow an arbitrary function to be passed to the client which is used instead of fetch.

The first option would be slightly more difficult to implement and maintain (doable though) for me, but would be easier for the user to use. Although if we were solely supporting node-fetch, I guess we could use the 2nd option anyway since node-fetch is compatible (and functionally identical) to node's fetch support.

The second option would be more flexible for the user, at the expense of being possibly more time consuming for them to create their own function.


Tell me what you think anyway, there may be a better solution

**Comment by ChrisPhillips-cminion** [comment]
You are 100% riight. I didnt realise the nodejs without fetch was so far behind LTS, please reject this merge no issue.

**Comment by jamesatjaminit** [comment]
No worries, I'll likely still implement the second solution as it's bound to help someone at some point. However it won't be much of a priority now this is solved.

Thanks Chris!

**Pull request closed without merging**
